### /role/list
GET http://{{host}}/role/list?page=1&limit=10
Authorization: {{authorization}}

### /role/list/by_uid
GET http://{{host}}/role/list/by_uid?uid=1399536808257646594
Authorization: {{authorization}}