### Send POST request with json body
POST http://{{host}}/user/register
Content-Type: application/json

{
  "username": "admin",
  "password": "123123"
}

### /user/login
POST http://{{host}}/user/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123123"
}

### /user/info
GET http://{{host}}/user/info?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1aWQiOiIxMzc5MjUyMTAzNjUwMTQwMTYyIiwiZXhwIjoxNjIyMTA3NDk0LCJyb2xlcyI6WyJHVUVTVCIsIkFETUlOIl0sImF2YXRhciI6Imh0dHBzOi8vd2N5LWltZy5vc3MtY24tYmVpamluZy5hbGl5dW5jcy5jb20vaW1hZ2VzL2F2YXRhci9kZWZhdWx0X2F2YXRhci5qcGciLCJuYW1lIjoi6ICB566h55CG5ZGYIn0.YUEH_nUMREPsOq5xGx4TXj5fGVEU2NrInmLzogn3ToUwCSOSXahSOXYpi6X68A6-TYLYNm4mtvjg1ETp-LZj3WUnWAUJKqfI6hlQmCSj5PjOvBfd31DH1qFCECsj7pwU5neOeBYob_kwNXOAqOSRmpQpL0dOXqfiswXGAB49siNuhlbqEg3W9R0UkGU1do5dWzCCOliEICj0eSttAQKhPIzFmV9cTdLsBTxwPMBhLJaaRq9eO_oNqPKUqltj_SLmO0zdz5quoShc_DRb0xeuz_kuyksCr0LJ1SHaXDVPPXcl7dRoLRUcyL7eal-1MgVbO-gVpIpk9XD0qgJUsVaqQw
Content-Type: application/json
Authorization: {{authorization}}
